### ISSUE TITLE
No tips shown at startup

### ISSUE THREAD

**Issue by simone-gaiarin** [michaelb/vim-tips#19]
Hi,
I have installed vim-tips via plug but it does display nothing when I start vim.

If I add this to my vimrc it displays the tips in the shell before launching vim
```
runtime plugin/vim-tips.vim
let tip = GetTip()
echo tip
```

How can I make it display the tip in the command bar?

**Comment by michaelb** [comment]
Uhhh that quite weird.... In the _terminal_ from where you launched vim ??

Is your vim particularly slow to start up ? Maybe the default tip shows _just before_ vim redraws the screen ...


Could you move the snippet to the end of your configuration (loaded last) just in case?

**Comment by simone-gaiarin** [comment]
> Uhhh that quite weird.... In the _terminal_ from where you launched vim ??
Yes
![Screenshot_20220324_123956](https://user-images.githubusercontent.com/71336378/159909045-7af330a2-6d8b-4be4-acf4-65ab1b8eac7b.png)

This happen if I put the mentioned code in .vimrc

> Is your vim particularly slow to start up ? Maybe the default tip shows _just before_ vim redraws the screen ...

It is not slow. Is it there a way to debug the fact that a redraw happens?

> Could you move the snippet to the end of your configuration (loaded last) just in case?
It was already at the end

- What is not clear to me is: does this plugin requires a configuration (i.e. if I do not put anything in the .vimrc should it still work)?

**Comment by michaelb** [comment]
> Is it there a way to debug the fact that a redraw happens?

Not to my knowledge, but I'm quite novice in vim-fu

> What is not clear to me is: does this plugin requires a configuration 

It doesn't require configuration, however, if you wish to integrate with other plugins (like alpha for example) to show the tips elsewhere than the command area at startup, you should use the snippet to ensure vim-tips is loaded _before_ another plugin, and disable the default behavior 



To be honest, I don't know where to start tp debug this. This plugin basically defines a couples of list of tims, and randomly selects one, then 'echo s:tip'  it to the command area, so there's not much room for very strange bugs...
