### ISSUE TITLE
Add an option to disable calling vim-tips on Vimenter

### ISSUE THREAD

**Issue by h0adp0re** [michaelb/vim-tips#9]
If you use vim-tips programmatically, with the function `GetTip()`, you probably don't want it called automatically every time vim starts.

Something like this would be wonderful.

```vim
let g:vim_tips_disable_on_vimenter = 1
```

**Comment by michaelb** [comment]
You won't believe it, but that was actually pushed to dev 30 min ago

Let me merge it into master :smile:

**Comment by h0adp0re** [comment]
Wow, you continue to amaze me, haha. Thanks.
